# Generated by Django 3.2.6 on 2024-05-18 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_groups_alter_users_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_bags', models.BooleanField(default=True)),
                ('lifted_status', models.BooleanField(default=True)),
                ('total_pointes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pickup_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_waste_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pickup_transaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastename', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_images/')),
                ('kg', models.CharField(default='kg', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='waste_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waste_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('shop_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rcb_agreed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_ouner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PickupWastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('pointes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_transaction', models.ForeignKey(db_column='pickup_transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.pickuptransaction')),
                ('waste_type', models.ForeignKey(db_column='waste_type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.wastetype')),
            ],
            options={
                'db_table': 'pickup_waste_data',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pickuptransaction',
            name='shop_owner',
            field=models.ForeignKey(db_column='shop_owner_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.shopowner'),
        ),
    ]
