# Generated by Django 3.2.6 on 2024-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240518_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='shopowner_number',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
