# Generated by Django 3.2.6 on 2024-05-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shopowner_shopowner_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastetype',
            old_name='kg',
            new_name='quantity',
        ),
    ]
