# Generated by Django 3.2.6 on 2024-05-20 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_kg_wastetype_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='shopowner',
            name='user',
            field=models.ForeignKey(db_column='users_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopowner',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
