# Generated by Django 3.2.6 on 2024-05-20 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240520_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='user',
            field=models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
