# Generated by Django 3.2.6 on 2024-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_shopowner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('panshop', 'pan shop'), ('teashop', 'tea shop'), ('hosptial', 'hosptial')], default='', max_length=100, null=True),
        ),
    ]
