# Generated by Django 3.2.6 on 2024-06-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shopowner_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shopowner',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('panshop', 'pan shop'), ('teashop', 'tea shop'), ('hosptial', 'hosptial'), ('restrant', 'restrant')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('employee', 'employee'), ('cluster', 'cluster')], default='admin', max_length=100, null=True),
        ),
    ]
