# Generated by Django 3.2.6 on 2024-06-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240601_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='points',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
